apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "souq-ai.fullname" . }}-results-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "souq-ai.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
