apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "souq-ai.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "1"
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: ssm-parameter-store
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Namespace }}-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Release.Namespace }}-secrets
