CATEGORY_TAXONOMY = {
    "Beverages": [
        "Soft Drinks / Sodas",
        "Bottled Water / Drinking Water",
        "Drink Mixes / Powdered Beverages",
        "Malt Drinks",
        "Juices & Fruit Drinks",
        "Coffee Beverages",
        "Tea Beverages",
        "Beverage Syrups",
        "Sports & Energy Drinks",
        "Dairy Beverages",
    ],
    "Dairy": [
        "Fresh Milk",
        "Butter & Margarine",
        "Fermented Dairy",
        "Cheese Products",
        "Dairy Cream",
        "Milk Powder",
        "Unsweetened Condensed Milk",
        "Sweetened Condensed Milk",
    ],
    "Meat / Fish / Poultry / Eggs": [
        "Fresh Meat",
        "Frozen Meat Products",
        "Processed Meat",
        "Fresh Poultry",
        "Frozen Poultry Products",
        "Processed Poultry",
        "Fresh Seafood",
        "Frozen Fish & Seafood",
        "Canned Seafood",
        "Deli Meats & Specialty Foods",
        "Fresh Eggs",
    ],
    "Fruits and Vegetables": [
        "Fresh Fruit",
        "Fresh Vegetables & Greens",
        "Dry Fruits",
        "Frozen Veggies",
        "Frozen Fruit",
        "Canned Vegetables",
        "Canned Fruits",
        "Nuts & Seeds",
        "Date Fruit",
    ],
    "Grocery": [
        "Cooking Oils & Ghee",
        "Rice & Grains",
        "Sauces & Condiments",
        "Pasta & Instant Noodles",
        "Spices & Seasonings",
        "Pickles & Relishes",
        "Vinegar & Dressings",
        "Sugar & Sweeteners",
        "Pulses & Grains",
        "Natural Honey",
        "Sweet Spreads",
        "Soup Mixes & Broth",
        "Cooking Ingredients",
        "Baking Flour",
        "Baking Mixes",
        "Breakfast Cereals",
        "Hot Cereals",
        "Granola Bars / Snack Bars",
        "Burger Mix",
        "Ready Meals",
        "Ready-to-Cook",
    ],
    "Desserts": [
        "Dessert Syrups & Toppings",
        "Shelf-Stable Desserts",
        "Frozen Ice Cream",
        "Frozen Treats",
        "Frozen Cakes",
        "Fresh Cakes",
        "Fresh Pastries",
        "Frozen Pastries",
        "Ethnic Desserts",
    ],
    "Confectionery": [
        "Chocolate Confectionery",
        "Hard Candy",
        "Gum",
        "Cookies & Biscuits",
        "Confectionery",
    ],
    "Snacks": [
        "Potato Chips / Crisps",
        "Fruit-Based Snacks",
        "Pretzels",
        "Trail Mix & Nuts",
        "Bakery Snacks",
    ],
    "Bakery": [
        "Bakery Bread",
    ],
    "Health and Beauty": [
        "Body Wash",
        "Skincare",
        "Haircare",
        "Shaving Products",
        "Dental Care",
        "Nail & Foot Care",
        "Women's Hygiene",
        "Perfumes",
        "Makeup",
        "Deodorants",
        "Medicines",
        "Medical Equipment",
        "Dietary Supplements",
        "Healthcare Products",
        "Herbal Products",
        "Birth Control",
        "Nursing Care",
    ],
    "Cleaning Products / Hygiene Products": [
        "Laundry Bleach",
        "Cleaning Supplies",
        "Dishwashing Products",
        "Sanitizers",
        "Multi-Surface Cleaners",
        "Toilet Cleaners",
        "Air Fresheners",
        "Laundry Care",
        "Pest Control",
    ],
    "Baby and Mother": [
        "Baby Food",
        "Diapers",
        "Infant Care",
        "Infant Nutrition",
        "Baby Accessories",
    ],
    "Paper Products and Disposables": [
        "Tissues",
        "Paper Products",
        "Trash Bags",
        "Aluminum Foil & Plastic Wrap",
        "Food Storage Containers",
    ],
    "Clothing and Footwear": [
        "Women's Apparel",
        "Men's Apparel",
        "Children's Clothing",
        "Fashion Accessories",
        "Shoes",
    ],
    "Electronics": [
        "Major Appliances",
        "Small Appliances",
        "Kitchen Electronics",
        "TVs & Accessories",
        "Consumer Electronics",
        "Video Games",
        "Smartphones",
        "Mobile Accessories",
        "Landline Phones",
        "Notebook Computer",
        "PC Components",
        "Storage Devices",
        "Networking Devices",
    ],
    "Other": [
        "Tableware",
        "Kitchen Cookware",
        "Home Furniture",
        "Home Decor",
        "Home Essentials",
        "Hardware Tools",
        "Lighting Fixtures",
        "Office Supplies",
        "Automotive Accessories",
        "Toys",
        "Animal Food",
        "Pet Supplies",
        "Outdoor Camping",
        "Fitness Equipment",
        "Power Batteries",
        "Jewelry",
        "Timepieces",
        "Luggage",
        "Luggage & Bags",
        "Bath Towels",
        "Bedding",
        "Table Linen",
        "Home Improvement",
        "Music Instruments",
        "Reading Materials",
        "Garden Supplies",
        "Unknown",
        "Advertisement / Promotional",
        "Other",
    ],
    "Tobacco": [
        "Tobacco Products",
        "Smoking Accessories",
    ],
}

MAIN_CATEGORIES = list(CATEGORY_TAXONOMY.keys())
ALL_SUBCATEGORIES = sorted({sub for subs in CATEGORY_TAXONOMY.values() for sub in subs})


def format_taxonomy_for_prompt():
    return "\n".join(f"{main}: {', '.join(subs)}" for main, subs in CATEGORY_TAXONOMY.items())
